#!/bin/bash
pytest --cov=src/rattlesnake --cov-report=html --cov-report=xml --cov-report=term-missing --cov-config=.coveragerc
pytest tests/test_acquisition.py
ruff check src/rattlesnake --exclude tests,user_interface