# -*- coding: utf-8 -*-
"""
This file defines a Time Signal Generator environment where a signal can be
loaded and played directly to the output devices.  This is perhaps the simplest
control type that might be implemented by the controller, so start here when
designing new control types.

Rattlesnake Vibration Control Software
Copyright (C) 2021  National Technology & Engineering Solutions of Sandia, LLC
(NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
Government retains certain rights in this software.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
from .abstract_environment import EnvironmentMetadata
from .environment_utilities import ControlTypes
from ..utilities import VerboseMessageQueue
import copy
import multiprocessing as mp
import multiprocessing.sharedctypes  # pylint: disable=unused-import
from multiprocessing.queues import Queue
import netCDF4 as nc4
import numpy as np


CONTROL_TYPE = ControlTypes.TIME
TEST_LEVEL_THRESHOLD = 1.01
MAX_RESPONSES_TO_PLOT = 20
MAX_SAMPLES_TO_PLOT = 100000


class TimeQueues:
    """A set of queues used by the Time environment"""

    def __init__(
        self,
        environment_command_queue: VerboseMessageQueue,
        gui_update_queue: mp.queues.Queue,
        controller_communication_queue: VerboseMessageQueue,
        data_in_queue: mp.queues.Queue,
        data_out_queue: mp.queues.Queue,
        log_file_queue: VerboseMessageQueue,
    ):
        """
        Creates a namespace to store all the queues used by the Time Environment

        Parameters
        ----------
        environment_command_queue : VerboseMessageQueue
            Queue from which the environment will receive instructions.
        gui_update_queue : mp.queues.Queue
            Queue to which the environment will put GUI updates.
        controller_communication_queue : VerboseMessageQueue
            Queue to which the environment will put global contorller instructions.
        data_in_queue : mp.queues.Queue
            Queue from which the environment will receive data from acquisition.
        data_out_queue : mp.queues.Queue
            Queue to which the environment will write data for output.
        log_file_queue : VerboseMessageQueue
            Queue to which the environment will write log file messages.
        """
        self.environment_command_queue = environment_command_queue
        self.gui_update_queue = gui_update_queue
        self.controller_communication_queue = controller_communication_queue
        self.data_in_queue = data_in_queue
        self.data_out_queue = data_out_queue
        self.log_file_queue = log_file_queue


class TimeParameters(EnvironmentMetadata):
    """Storage container for parameters used by the Time Environment"""

    def __init__(self, sample_rate, output_signal, cancel_rampdown_time):
        """
        Container to hold signal processing parameters for the Time environment

        Parameters
        ----------
        sample_rate : int
            Number of samples per second that the controller runs.
        output_signal : np.ndarray
            Signal that will be generated by the sources, 2D array (n_outputs x
            n_samples)
        cancel_rampdown_time : float
            Time used to decay the signal to zero if the environment is stopped.
            Prevents "hard stops" from damaging equipment.

        """
        self.sample_rate = sample_rate
        self.output_signal = output_signal
        self.cancel_rampdown_time = cancel_rampdown_time

    @property
    def signal_samples(self):
        """The number of samples in the signal"""
        return self.output_signal.shape[-1]

    @property
    def output_channels(self):
        """The number of output channels in the signal"""
        return self.output_signal.shape[0]

    @property
    def signal_time(self):
        """The length of the signal in seconds"""
        return self.signal_samples / self.sample_rate

    @property
    def cancel_rampdown_samples(self):
        """The number of samples required to ramp down the signal when cancelled"""
        return int(self.cancel_rampdown_time * self.sample_rate)

    def store_to_netcdf(
        self,
        netcdf_group_handle: nc4._netCDF4.Group,  # pylint: disable=c-extension-no-member
    ):
        """
        Stores parameters to a netCDF group so they can be recovered.

        Parameters
        ----------
        netcdf_group_handle : nc4._netCDF4.Group
            Reference to the netCDF4 group in which the environment data should
            be stored.

        """
        netcdf_group_handle.cancel_rampdown_time = self.cancel_rampdown_time
        # Save the output signal
        netcdf_group_handle.createDimension("output_channels", self.output_channels)
        netcdf_group_handle.createDimension("signal_samples", self.signal_samples)
        var = netcdf_group_handle.createVariable("output_signal", "f8", ("output_channels", "signal_samples"))
        var[...] = self.output_signal

    @classmethod
    def from_ui(cls, ui):
        """Creates a TimeParameters object from the user interface

        Parameters
        ----------
        ui : TimeUI
            A Time User Interface

        Returns
        -------
        test_parameters : TimeParameters
            Parameters corresponding to the data in the user interface.

        """
        return cls(
            sample_rate=ui.definition_widget.output_sample_rate_display.value(),
            output_signal=ui.signal,
            cancel_rampdown_time=ui.definition_widget.cancel_rampdown_selector.value(),
        )
