[book]
authors = ["Daniel P. Rohe", "Ryan Schultz", "Norman Hunter"]
description = "Rattlesnake is a combined-environments, multiple input/multiple output control system for dynamic excitation of structures under test."
language = "en"
# multilingual = false #  multilingual key removed in mdBook 0.5.0, released late 2024
src = "src"
title = "Rattlesnake Vibration Controller"

# did work for local LaTeX, uses KaTeX, which is faster than MathJax
[preprocessor.katex]
after = ["links"] # By setting after = ["links"], you ensure that link processing happens before math rendering, which is the recommended practice to prevent conflicts with special characters.

# reference font modifications made in the theme/custom.css file
[output.html]
additional-css = ["theme/custom.css"]

[preprocessor.bib]
# The name of your .bib file, relative to the src directory
# Ensure it runs after links but before katex
after = ["links"]
before = ["katex"]
bibliography = "bibliography.bib"

# Optional: Set the title for the automatically generated bibliography chapter
title = "Bibliography"

# Optional: Render the entire bibliography ("all") or only cited entries ("cited")
render-bib = "cited"
