# name: Deploy mdBook
# name: # keep this field blank to automatically show the filename that triggers it in the CD/CD web UI
name: mdbook.yml
on:
  push:
    branches:
      - main
      - dev
      - "*doc"

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo Binaries
        uses: actions/cache@v3
        with:
          path: /usr/local/cargo/bin
          # This key creates a unique cache for your specific tools
          key: ${{ runner.os }}-mdbook-tools-${{ hashFiles('**/book.toml') }}
          restore-keys: |
            ${{ runner.os }}-mdbook-tools-

      - name: Install mdBook and preprocessors
        run: |
          # Only installs if the binaries don't already exist in the cached path
          command -v mdbook >/dev/null 2>&1 || cargo install mdbook
          command -v mdbook-katex >/dev/null 2>&1 || cargo install mdbook-katex
          command -v mdbook-bib >/dev/null 2>&1 || cargo install mdbook-bib

      - name: Build mdBook
        run: mdbook build documentation/mdbook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/mdbook/book
          destination_dir: book
          keep_files: true
